# Generated by Django 4.2.30 on 2026-04-08 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0005_company_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título da Live')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('youtube_url', models.URLField(max_length=500, verbose_name='Link do YouTube')),
                ('start_time', models.DateTimeField(verbose_name='Horário de Início')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_events', to='attendance.company')),
            ],
            options={
                'verbose_name': 'Evento ao Vivo',
                'verbose_name_plural': 'Eventos ao Vivo',
            },
        ),
        migrations.CreateModel(
            name='LiveAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.branch', verbose_name='Filial')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='livestream.liveevent')),
            ],
            options={
                'verbose_name': 'Presença em Live',
                'verbose_name_plural': 'Presenças em Live',
            },
        ),
    ]
