# Generated by Django 4.2.30 on 2026-04-13 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_meeting_is_youtube_live_meeting_start_time_and_more'),
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.JSONField(verbose_name='Credenciais Google (JSON)')),
                ('channel_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do Canal')),
                ('channel_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título do Canal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_config', to='attendance.company')),
            ],
            options={
                'verbose_name': 'Configuração YouTube',
                'verbose_name_plural': 'Configurações YouTube',
            },
        ),
    ]
