# Generated by Django 4.2.30 on 2026-04-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_youtubeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveattendance',
            name='last_heartbeat',
            field=models.DateTimeField(auto_now=True, verbose_name='Último Sinal'),
        ),
        migrations.AlterField(
            model_name='liveattendance',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Entrada'),
        ),
    ]
