# Generated by Django 4.2.30 on 2026-04-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0003_liveattendance_last_heartbeat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubeconfig',
            options={'verbose_name': 'Configuração YouTube Global', 'verbose_name_plural': 'Configurações YouTube Global'},
        ),
        migrations.RemoveField(
            model_name='youtubeconfig',
            name='company',
        ),
        migrations.AddField(
            model_name='youtubeconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
    ]
