# Generated by Django 4.2.30 on 2026-04-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0004_alter_youtubeconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeconfig',
            name='channel_thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Thumbnail do Canal'),
        ),
    ]
