# Generated by Django 4.2.30 on 2026-04-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0005_youtubeconfig_channel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveattendance',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Presença Confirmada (Oficial)'),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição/Texto Base'),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Curtidas'),
        ),
        migrations.AddField(
            model_name='liveevent',
            name='status',
            field=models.CharField(choices=[('waiting', 'Sala de Espera'), ('live', 'Ao Vivo'), ('finished', 'Encerrada')], default='waiting', max_length=20),
        ),
        migrations.CreateModel(
            name='LiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('branch_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='livestream.liveevent')),
            ],
            options={
                'verbose_name': 'Mensagem do Chat',
                'verbose_name_plural': 'Mensagens do Chat',
                'ordering': ['created_at'],
            },
        ),
    ]
