# Generated by Django 4.2.30 on 2026-04-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0006_liveattendance_is_confirmed_liveevent_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveevent',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Exibir no Dashboard Público?'),
        ),
    ]
