# Generated by Django 4.2.29 on 2026-03-31 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_complaint_complaintcategory_urgencylevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('api_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('primary_color', models.CharField(default='#e63946', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.AlterField(
            model_name='complaintcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título do Curso'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='urgencylevel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='attendance.company'),
        ),
        migrations.AddField(
            model_name='complaintcategory',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_categories', to='attendance.company'),
        ),
        migrations.AddField(
            model_name='course',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='attendance.company'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='attendance.company'),
        ),
        migrations.AddField(
            model_name='urgencylevel',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urgency_levels', to='attendance.company'),
        ),
        migrations.AlterUniqueTogether(
            name='complaintcategory',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('company', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='urgencylevel',
            unique_together={('company', 'name')},
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Filial')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='attendance.company')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'unique_together': {('company', 'name')},
            },
        ),
    ]
