# Generated by Django 4.2.30 on 2026-04-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_company_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_youtube_live',
            field=models.BooleanField(default=False, verbose_name='Agendar no YouTube?'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário da Reunião'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='youtube_broadcast_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='youtube_stream_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
