# Generated by Django 4.2.30 on 2026-04-13 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0003_liveattendance_last_heartbeat_and_more'),
        ('attendance', '0006_meeting_is_youtube_live_meeting_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='live_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunion_meeting', to='livestream.liveevent'),
        ),
    ]
