# Generated by Django 4.2.30 on 2026-04-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_meeting_live_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição (Suporta Emojis)'),
        ),
    ]
