# Generated by Django 4.2.30 on 2026-04-14 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0008_meeting_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador Master'), ('OUVIDOR', 'Analista de Ouvidoria'), ('CONTEUDISTA', 'Gestor de Conteúdo'), ('AUDITOR', 'Auditor de Relatórios')], default='OUVIDOR', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Equipe',
                'verbose_name_plural': 'Perfis de Equipe',
            },
        ),
    ]
