# Generated by Django 4.2.30 on 2026-04-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_complaint_is_read_evaluation_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='5543996404350', max_length=20, verbose_name='WhatsApp do Capelão')),
                ('contact_email', models.EmailField(default='contato@exemplo.com', max_length=254, verbose_name='E-mail de Contato Exibido')),
                ('notify_email', models.EmailField(default='admin@exemplo.com', max_length=254, verbose_name='E-mail que recebe notificações')),
                ('address', models.TextField(default='Rua Gualuvira, 265, Londrina - PR', verbose_name='Endereço no Rodapé')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Global',
                'verbose_name_plural': 'Configurações Globais',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('company', models.CharField(max_length=255, verbose_name='Empresa')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead / Contato Site',
                'verbose_name_plural': 'Leads / Contatos Site',
            },
        ),
    ]
