# Generated by Django 4.2.30 on 2026-04-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_globalconfig_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('answer', models.TextField(verbose_name='Resposta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Item de FAQ',
                'verbose_name_plural': 'Itens de FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Legenda')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Fotos da Galeria',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Colaborador')),
                ('role', models.CharField(max_length=150, verbose_name='Cargo')),
                ('company_name', models.CharField(max_length=150, verbose_name='Empresa')),
                ('message', models.TextField(verbose_name='Depoimento')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto de Perfil')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado?')),
                ('show_on_home', models.BooleanField(default=False, verbose_name='Exibir na Home?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_testimonials', to='attendance.company')),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
            },
        ),
    ]
