# Generated by Django 4.2.30 on 2026-04-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_faqitem_galleryimage_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='formation_year',
            field=models.IntegerField(default=2004, verbose_name='Ano de Formação na Capelania'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='address',
            field=models.TextField(default='Av. Des. Mário da Silva Nunes, 717 - Jardim Limoeiro, Serra - ES, 29164-044', verbose_name='Endereço no Rodapé'),
        ),
    ]
